'use client';
import BankReportBuilder, { BankReportBuilderProps } from '../../BankReportBuilder';
import { BankConfig } from '@/lib/bank-fields';

export const ADITYA_BIRLA_HOUSING_HLLAP_CONFIG: BankConfig = {
  bankId: 'ADITYA BIRLA HOUSING FINANCE LTD',
  subTemplateId: 'HL-LAP',
  displayName: 'Aditya Birla Housing Finance Ltd',
  navSections: [
    { id: 'section-1', title: 'Header & Basic Details' },
    { id: 'section-2', title: 'Surrounding & Locality' },
    { id: 'section-3', title: 'Property Details' },
    { id: 'section-4', title: 'Sanction Plan & Documents' },
    { id: 'section-5', title: 'Setbacks & BUA' },
    { id: 'section-6', title: 'Valuation Details' },
    { id: 'section-7', title: 'Boundaries' },
    { id: 'section-8', title: 'Remarks & Declaration' },
    { id: 'section-9', title: 'Photographs' },
    { id: 'section-10', title: 'Location Map' },
    { id: 'section-11', title: 'Deviations / Observations' },
  ],
  fieldLabels: {
    loanApplicationNo: 'Deal Number',
    ownerName: 'Applicant Name(s)',
    ownerAddress: 'Address as per request',
  },
  extraFields: {
    // ── HEADER / TOP BANNER ──
    'section-1': [
      { key: 'dealNumber', label: 'Deal Number' },
      { key: 'assetId', label: 'Asset ID' },
      { key: 'typeOfCase', label: 'Type of Case', default: 'Home Loan' },
      { key: 'productType', label: 'Product Type', default: 'Home Loan' },
      { key: 'valuerFeedback', label: 'Valuer Feedback', default: 'Positive' },
      { key: 'contactedPerson', label: 'Contacted Person' },
      { key: 'relationWithCustomer', label: 'Relation with Customer', default: 'Self' },
      { key: 'sellerName', label: 'Seller' },
      { key: 'contactNo', label: 'Contact No' },
      // ── BASIC DETAILS (1-4) ──
      { key: 'originallyTypeOfProperty', label: '2. Originally type of property' },
      { key: 'currentUsage', label: 'Current Usage', default: 'Residential Flat' },
      { key: 'addressAsPerRequest', label: '3. Address as per request', type: 'textarea', span: 2 },
      { key: 'addressAsPerDocument', label: 'Address as per document', type: 'textarea', span: 2 },
      { key: 'addressAsPerSite', label: 'Address as per Site', type: 'textarea', span: 2 },
      { key: 'projectColonyLayoutName', label: 'Project/Colony/Layout Name' },
      { key: 'unitFlatBungalowPlotHouseNo', label: 'Unit/Flat no/ Bungalow/Plot/House no.' },
      { key: 'floorNo', label: 'Floor No' },
      { key: 'buildingName', label: 'Building Name' },
      { key: 'wingName', label: 'Wing Name' },
      { key: 'khasraNo', label: 'S.No/G.No/Khasra No', type: 'textarea' },
      { key: 'closeVicinityLandmark', label: 'Close Vicinity/Landmark' },
      { key: 'streetName', label: 'Street Name' },
      { key: 'villageName', label: 'Village Name' },
      { key: 'city', label: 'City' },
      { key: 'stateName', label: 'State', default: 'Odisha' },
      { key: 'mainLocalityOfProperty', label: 'Main Locality of the Property' },
      { key: 'subLocality', label: 'Sub Locality' },
      { key: 'pinCodeOfProperty', label: 'Pin code of the Property' },
      { key: 'latitude', label: 'Latitude' },
      { key: 'longitude', label: 'Longitude' },
      { key: 'valuedBefore', label: '4. Has the valuator valued this property before, If yes, when, for whom', default: 'No' },
    ],

    // ── SURROUNDING & LOCALITY DETAILS (5-11) ──
    'section-2': [
      { key: 'locationType', label: '5. Type (Comm, Res, Ind, Mix)', default: 'Residential' },
      { key: 'localityLevel', label: 'Locality (Low, Medium, Posh)', default: 'Medium' },
      { key: 'siteDevStatus', label: 'Site is (Dev, Under Dev, Developing)', default: 'Developed' },
      { key: 'proximityToCivicAmenities', label: 'Proximity to civic amenities/public transport', default: 'Good' },
      { key: 'railwayStationDistance', label: 'Railway Station' },
      { key: 'busStopDistance', label: 'Bus Stop' },
      { key: 'distanceFromCityCentre', label: '6. Distance from City Centre' },
      { key: 'distanceFromCityCentreUnit', label: 'Unit', default: 'Km' },
      { key: 'natureOfApproachRoad', label: '7. Nature of approach Road', default: 'Bitumen Road' },
      { key: 'approachRoadWidth', label: '8. Approach Road width' },
      { key: 'approachRoadWidthUnit', label: 'Unit', default: 'Feet' },
      { key: 'approachAsPerSite', label: '9. Approach to the property as per Site', default: 'Clear' },
      { key: 'approachAsPerDocs', label: '10. Approach to the property as per Docs', default: 'Clear' },
      { key: 'securityObservation', label: '11. Any observation which affects the security', default: 'NA' },
    ],

    // ── PROPERTY DETAILS (12-16) ──
    'section-3': [
      { key: 'occupiedBy', label: '12. Occupied By', default: 'Vacant' },
      { key: 'nameOfOccupant', label: 'Name of Occupant', default: 'NA' },
      { key: 'noOfTenants', label: 'No of Tenants', default: 'NA' },
      { key: 'relationWithApplicant', label: 'Relation with applicant', default: 'NA' },
      { key: 'propertyDemarcation', label: '13. Property Demarcation', default: 'Yes' },
      { key: 'propertyIdentifiedYN', label: 'Property Identified (Y/N)', default: 'Yes' },
      { key: 'propertyIdentifiedThrough', label: 'Property Identified through' },
      { key: 'typeOfStructure', label: 'Type of structure', default: 'R.C.C' },
      { key: 'landPlotAreaUDS', label: 'Land/Plot Area -UDS' },
      { key: 'landPlotAreaUDSUnit', label: 'Unit', default: 'Sqft' },
      { key: 'noOfBlocks', label: 'No of Blocks' },
      { key: 'noOfUnitsOnEachFloor', label: 'No of Units on each floor' },
      { key: 'noOfFloors', label: 'No. of Floors' },
      { key: 'noOfLifts', label: 'No. of Lifts' },
      { key: 'amenitiesAvailable', label: 'Amenities Available', default: 'Yes' },
      { key: 'deliveryAgency', label: 'Delivery Agency' },
      { key: 'propertyLocatedOnFloor', label: '14. Property located on Floor' },
      { key: 'unitConfiguration', label: 'Unit Configuration' },
      { key: 'carpetArea', label: 'Carpet area' },
      { key: 'carpetAreaUnit', label: 'Unit', default: 'Sqft' },
      { key: 'sbuaOf', label: 'SBUA of' },
      { key: 'sbuaUnit', label: 'Unit', default: 'Sqft' },
      { key: 'viewFromProperty', label: 'View from property', default: 'Good' },
      { key: 'constructionQualityExteriors', label: '15. Construction Quality - Exteriors', default: 'Good' },
      { key: 'constructionQualityInteriors', label: 'Construction Quality - Interiors', default: 'Good' },
      { key: 'ageOfProperty', label: '16. Age of the property (Yrs)' },
      { key: 'residualAge', label: 'Residual age (Yrs)' },
    ],

    // ── SANCTION PLAN APPROVAL & OTHER DOCUMENTS DETAILS (17-23) ──
    'section-4': [
      { key: 'sanctionPlanAvailable', label: '17. Sanction Plan Available', default: 'NA' },
      { key: 'layoutPlanApprovalNo', label: '18. Layout Plan - Approval No', default: 'N.A' },
      { key: 'layoutPlanDateOfApproval', label: 'Layout Plan - Date of Approval', default: 'N.A' },
      { key: 'layoutPlanExpiryDate', label: 'Layout Plan - Expiry Date', default: 'N.A' },
      { key: 'layoutPlanSanctioningAuthority', label: 'Layout Plan - Sanctioning Authority', default: 'N.A' },
      { key: 'buildingPlanApprovalNo', label: 'Building Plan - Approval No' },
      { key: 'buildingPlanDateOfApproval', label: 'Building Plan - Date of Approval' },
      { key: 'buildingPlanExpiryDate', label: 'Building Plan - Expiry Date', default: 'N.A' },
      { key: 'buildingPlanSanctioningAuthority', label: 'Building Plan - Sanctioning Authority' },
      { key: 'constructionPermissionApprovalNo', label: 'Construction Permission - Approval No', default: 'N.A' },
      { key: 'constructionPermissionDateOfApproval', label: 'Construction Permission - Date of Approval', default: 'N.A' },
      { key: 'constructionPermissionExpiryDate', label: 'Construction Permission - Expiry Date', default: 'N.A' },
      { key: 'constructionPermissionSanctioningAuthority', label: 'Construction Permission - Sanctioning Authority', default: 'N.A' },
      { key: 'constructionCertificateApprovalNo', label: 'Construction Certificate - Approval No', default: 'N.A' },
      { key: 'constructionCertificateDateOfApproval', label: 'Construction Certificate - Date of Approval', default: 'N.A' },
      { key: 'constructionCertificateExpiryDate', label: 'Construction Certificate - Expiry Date', default: 'N.A' },
      { key: 'constructionCertificateSanctioningAuthority', label: 'Construction Certificate - Sanctioning Authority', default: 'N.A' },
      { key: 'constructionCommencementDate', label: '19. Construction commencement date' },
      { key: 'expectedCompletionDate', label: 'Expected Completion Date' },
      { key: 'ownershipType', label: '20. Ownership Type (Free / Lease Hold)', default: 'FREEHOLD' },
      { key: 'propertyDocsVerification', label: '21. Property documents verification details' },
      { key: 'propertyJurisdiction', label: '22. Property Jurisdiction' },
      { key: 'permissibleZoning', label: '23. Permissible zoning as per master plan' },
      { key: 'usageAsPerSite', label: 'Usage As per Site' },
    ],

    // ── SETBACKS & BUA AREA (24-26) ──
    'section-5': [
      { key: 'demolitionList', label: '24. Whether property under demolition list as per authority (Y/N)', default: 'No' },
      { key: 'setbackFrontPlan', label: '25. Setback Front - As per plan/Byelaws (Fts)', default: 'N.A' },
      { key: 'setbackFrontSite', label: 'Setback Front - As per site (Fts)', default: 'N.A' },
      { key: 'setbackSide1Plan', label: 'Setback Side1(Left) - As per plan/Byelaws (Fts)', default: 'N.A' },
      { key: 'setbackSide1Site', label: 'Setback Side1(Left) - As per site (Fts)', default: 'N.A' },
      { key: 'setbackSide2Plan', label: 'Setback Side2(Right) - As per plan/Byelaws (Fts)', default: 'N.A' },
      { key: 'setbackSide2Site', label: 'Setback Side2(Right) - As per site (Fts)', default: 'N.A' },
      { key: 'setbackRearPlan', label: 'Setback Rear - As per plan/Byelaws (Fts)', default: 'N.A' },
      { key: 'setbackRearSite', label: 'Setback Rear - As per site (Fts)', default: 'N.A' },
      { key: 'buaFloor1Name', label: '26. BUA Floor 1 Name', default: 'First' },
      { key: 'buaFloor1Plan', label: 'BUA Floor 1 - As per plan/Byelaws (Sqft)', default: 'N.A' },
      { key: 'buaFloor1Site', label: 'BUA Floor 1 - As per site (Sqft)', default: 'N.A' },
      { key: 'buaFloor2Name', label: 'BUA Floor 2 Name' },
      { key: 'buaFloor2Plan', label: 'BUA Floor 2 - As per plan/Byelaws (Sqft)' },
      { key: 'buaFloor2Site', label: 'BUA Floor 2 - As per site (Sqft)' },
      { key: 'buaFloor3Name', label: 'BUA Floor 3 Name' },
      { key: 'buaFloor3Plan', label: 'BUA Floor 3 - As per plan/Byelaws (Sqft)' },
      { key: 'buaFloor3Site', label: 'BUA Floor 3 - As per site (Sqft)' },
      { key: 'totalBuaPlan', label: 'Total BUA (In Sft.) - Plan', default: 'N.A' },
      { key: 'totalBuaSite', label: 'Total BUA (In Sft.) - Site', default: 'N.A' },
    ],

    // ── VALUATION DETAILS (27) ──
    'section-6': [
      { key: 'propertyTypeBungalow', label: 'Property Type', default: 'Bungalow' },
      { key: 'landAreaMeasurement', label: 'Land Area - Unit of Measurement', default: 'Sqft' },
      { key: 'landAreaValue', label: 'Land Area - Area', default: '0' },
      { key: 'landAreaRatePerUnit', label: 'Land Area - Rate/unit', default: '0' },
      { key: 'landAreaAmount', label: 'Land Area - Amount', default: '0' },
      { key: 'parkingStiltBuaUnit', label: 'Parking/Stilt BUA - Unit', default: 'Sqft' },
      { key: 'parkingStiltBuaArea', label: 'Parking/Stilt BUA - Area', default: '0' },
      { key: 'parkingStiltBuaRate', label: 'Parking/Stilt BUA - Rate/unit', default: '0' },
      { key: 'parkingStiltBuaAmount', label: 'Parking/Stilt BUA - Amount', default: '0' },
      { key: 'buaSbuaUnit', label: 'BUA/SBUA - Unit', default: 'Sqft' },
      { key: 'buaSbuaArea', label: 'BUA/SBUA - Area' },
      { key: 'buaSbuaRate', label: 'BUA/SBUA - Rate/unit' },
      { key: 'buaSbuaAmount', label: 'BUA/SBUA - Amount' },
      { key: 'constructionProgress', label: 'Construction Progress', default: 'Complete in all respect' },
      { key: 'percentCompletion', label: '27. % Completion', default: '100' },
      { key: 'percentRecommendation', label: '% Recommendation', default: '100' },
      { key: 'noOfCarParks', label: 'No of Car Parks', default: '0' },
      { key: 'carParkingCharges', label: 'Car Parking Charges Lumpsum (INR)', default: '0' },
      { key: 'edcIdcLumpsum', label: 'EDC,IDC Lumpsum(INR)', default: '0' },
      { key: 'plcChargesLumpsum', label: 'PLC Charges Lumpsum(INR)', default: '0' },
      { key: 'powerBackup', label: 'Power Backup', default: '0' },
      { key: 'interiorsAmenities', label: 'Interiors/Amenities', default: '0' },
      { key: 'interiorsPercentCompletion', label: 'Interiors % completion', default: '0' },
      { key: 'totalComponentA', label: 'Total of Component A on Completion' },
      { key: 'totalComponentB', label: 'Total of Component B on Completion', default: '0' },
      { key: 'totalMarketValueOnCompletion', label: 'Total Market Value of Property on Completion (A+B)' },
      { key: 'totalMarketValueOnCompletionWords', label: 'Total Market Value of Property on Completion in Words' },
      { key: 'totalMarketValueAsOnDate', label: 'Total Market Value of Property as on Date (A+B)' },
      { key: 'guidelineValueOfProperty', label: 'Guideline Value of The Property', default: 'NA' },
      { key: 'distressSaleValue', label: 'Distress Sale Value as on date' },
      { key: 'approxRentals', label: 'Approx. Rentals in case of 100% complete property' },
    ],

    // ── BOUNDARIES (28) ──
    'section-7': [
      { key: 'boundaryDocsNorth', label: 'As per Docs - North', default: 'NA' },
      { key: 'boundaryDocsEast', label: 'As per Docs - East', default: 'NA' },
      { key: 'boundaryDocsSouth', label: 'As per Docs - South', default: 'NA' },
      { key: 'boundaryDocsWest', label: 'As per Docs - West', default: 'NA' },
      { key: 'boundaryApprovedNorth', label: 'As per Approved plan key map - North' },
      { key: 'boundaryApprovedEast', label: 'As per Approved plan key map - East' },
      { key: 'boundaryApprovedSouth', label: 'As per Approved plan key map - South' },
      { key: 'boundaryApprovedWest', label: 'As per Approved plan key map - West' },
      { key: 'boundaryAtSiteNorth', label: 'At site - North' },
      { key: 'boundaryAtSiteEast', label: 'At site - East' },
      { key: 'boundaryAtSiteSouth', label: 'At site - South' },
      { key: 'boundaryAtSiteWest', label: 'At site - West' },
      { key: 'boundariesMatching', label: '28. Boundaries Matching' },
    ],

    // ── REMARKS & DECLARATION ──
    'section-8': [
      { key: 'remarksText', label: 'Remarks', type: 'textarea', span: 2 },
      { key: 'declarationText', label: 'Declaration', type: 'textarea', span: 2 },
    ],

    // ── DEVIATIONS / OBSERVATIONS ──
    'section-11': [
      { key: 'deviationPropertyAddress', label: 'Property Address (for Deviation page)', type: 'textarea', span: 2 },
      { key: 'deviationsObservations', label: 'Deviations/Observations', type: 'textarea', span: 2 },
    ],
  },
  defaultValues: {
    purpose: 'Home Loan / LAP',
    branchName: 'Bhubaneswar',
    state: 'Odisha',
  },
};

export default function AdityaBirlaHousingHLLAP(props: BankReportBuilderProps) {
  return <BankReportBuilder config={ADITYA_BIRLA_HOUSING_HLLAP_CONFIG} {...props} />;
}
