/**
 * AI Valuation Predictor — Data-Driven Prediction Engine
 * 
 * Uses trained statistical lookup tables from model_weights.json
 * (generated by ML_integration/scripts/train_model.js from real/dummy data)
 * instead of hardcoded heuristic values.
 * 
 * Falls back to heuristic defaults only when no trained data exists
 * for a given combination of inputs.
 */

import modelWeights from './model_weights.json';

// ─── Types ──────────────────────────────────────────────────────

export interface Suggestion {
  value: string;
  confidence: number;      // 0.0 – 1.0
  source: 'heuristic' | 'ml' | 'llm' | 'calculated';
  label: string;           // Human-readable field label
  section: number;         // Which section this field belongs to
  fieldKey: string;        // The ReportFields key
}

export interface PredictionInput {
  [key: string]: any;
}

export interface PredictionResult {
  suggestions: Record<string, Suggestion>;
  filledCount: number;
  totalFields: number;
  overallConfidence: number;
}

// ─── Trained Model Data ─────────────────────────────────────────

const weights: any = modelWeights;
const MODEL_ROW_COUNT = weights.metadata?.rowCount || 0;

// Confidence boost when using trained data vs hardcoded fallback
function trainedConfidence(baseConf: number, sampleCount: number): number {
  // More samples → higher confidence, capped at 0.92
  const sampleBoost = Math.min(sampleCount / 50, 1) * 0.15;
  return Math.min(baseConf + sampleBoost, 0.92);
}

// ─── All trackable fields for filled/total count ────────────────

const ALL_FIELD_KEYS = [
  // Section 1
  'propertyType', 'ownerName', 'ownerAddress', 'city', 'pincode', 'landmark',
  'loanApplicationNo', 'documentHolderName', 'dateOfInspection', 'dateOfValuation',
  'bankName', 'branchName', 'to',
  // Section 2
  'wardNo', 'vicinity', 'classOfLocality', 'approachRoadWidth', 'plotDemarcated',
  'distanceRailwayStation', 'distanceBusStop', 'distanceHospital',
  'propertyIdentification', 'proximityToFacilities',
  // Section 3
  'usageType', 'additionalAmenities', 'legalStatus',
  // Section 4
  'premisesType', 'occupiedBy', 'isPropertyRented', 'propertyTaxation',
  'boundaryNorth', 'boundarySouth', 'boundaryEast', 'boundaryWest',
  // Section 5
  'structureType', 'numberOfFloors', 'numberOfWings', 'unitsPerFloor',
  'internalComposition', 'numberOfLifts', 'ageOfProperty', 'ageOfPropertyActual',
  'estimatedFutureLife', 'exteriors', 'qualityOfConstruction',
  'flooringType', 'roofType', 'qualityOfFixtures',
  // Section 6
  'constructionApproved', 'approvalDetails', 'constructionPermission',
  'violationsObserved', 'conformsToByelaws', 'documentsVerified',
  // Section 8
  'landArea', 'landAreaUnit', 'govtLandRate', 'landRatePerUnit',
  'recommendedRateBasis', 'buaAsPerApprovals',
  // Section 9
  'marketability', 'valuationResult', 'realizablePct', 'distressPct',
  'replacementCost', 'deviations', 'guidelineValue',
  // Section 10
  'demarcation', 'possession', 'remarks', 'representativeName',
];

// ─── Helpers ────────────────────────────────────────────────────

function isFilled(val: any): boolean {
  if (val === null || val === undefined) return false;
  if (typeof val === 'string') return val.trim().length > 0;
  if (Array.isArray(val)) return val.length > 0;
  return true;
}

function getVal(fields: PredictionInput, key: string): string {
  const v = fields[key];
  return typeof v === 'string' ? v.trim() : '';
}

// ─── Heuristic fallback: Structure life spans ───────────────────

const STRUCTURE_LIFE_FALLBACK: Record<string, number> = {
  'RCC': 60, 'Load Bearing': 50, 'Steel Structure': 55,
  'Composite Structure': 55, 'Industrial Shed': 40,
  'A/C Sheet': 30, 'G/I Sheet': 25, 'Asbestos Roofing': 25,
};

// ─── Prediction Rules (Data-Driven) ─────────────────────────────

type PredictionRule = {
  fieldKey: string;
  label: string;
  section: number;
  requires: string[];
  predict: (fields: PredictionInput) => { value: string; confidence: number; source: Suggestion['source'] } | null;
};

const PREDICTION_RULES: PredictionRule[] = [

  // ── Estimated Future Life ──────────────────────────────────
  {
    fieldKey: 'estimatedFutureLife',
    label: 'Estimated Future Life',
    section: 5,
    requires: ['structureType'],
    predict: (fields) => {
      const structType = getVal(fields, 'structureType');
      
      // Try trained data first
      const trained = weights.futureLifeByStructure?.[structType];
      let totalLife: number;
      let source: Suggestion['source'] = 'ml';
      let baseConf = 0.7;

      if (trained && trained.medianTotalLife) {
        totalLife = trained.medianTotalLife;
        baseConf = trainedConfidence(0.75, trained.count);
      } else {
        // Fallback to heuristic
        totalLife = STRUCTURE_LIFE_FALLBACK[structType] || 50;
        source = 'heuristic';
        baseConf = 0.6;
      }

      // Parse age
      const ageActual = getVal(fields, 'ageOfPropertyActual');
      const ageRange = getVal(fields, 'ageOfProperty');
      let ageYears = 0;

      if (ageActual) {
        ageYears = parseInt(ageActual) || 0;
        baseConf += 0.1; // age known → more confident
      } else if (ageRange) {
        const match = ageRange.match(/(\d+)-(\d+)/);
        if (match) ageYears = Math.round((parseInt(match[1]) + parseInt(match[2])) / 2);
        else if (ageRange.includes('>50')) ageYears = 55;
      }

      const futureLife = Math.max(totalLife - ageYears, 3);
      return { value: `${futureLife} Years`, confidence: Math.min(baseConf, 0.92), source };
    },
  },

  // ── Quality of Construction ────────────────────────────────
  {
    fieldKey: 'qualityOfConstruction',
    label: 'Quality of Construction',
    section: 5,
    requires: ['structureType'],
    predict: (fields) => {
      const structType = getVal(fields, 'structureType');
      const ageActual = getVal(fields, 'ageOfPropertyActual');
      const age = parseInt(ageActual) || 0;

      // Age bucket matching train_model.js
      let ageBucket: string;
      if (age < 5) ageBucket = '0-4';
      else if (age < 15) ageBucket = '5-14';
      else if (age < 25) ageBucket = '15-24';
      else if (age < 35) ageBucket = '25-34';
      else ageBucket = '35+';

      const key = `${structType}|${ageBucket}`;
      const trained = weights.qualityByStructureAge?.[key];

      if (trained && trained.mode) {
        const conf = trainedConfidence(0.65, trained.count);
        return { value: trained.mode, confidence: conf, source: 'ml' };
      }

      // Heuristic fallback
      const locality = getVal(fields, 'classOfLocality');
      if (structType === 'RCC' && ['Elite', 'Posh', 'High Class'].includes(locality) && age < 15) {
        return { value: 'Very Good', confidence: 0.6, source: 'heuristic' };
      }
      if (structType === 'RCC' && age < 25) {
        return { value: 'Good', confidence: 0.55, source: 'heuristic' };
      }
      if (['A/C Sheet', 'G/I Sheet', 'Asbestos Roofing'].includes(structType)) {
        return { value: 'Average', confidence: 0.5, source: 'heuristic' };
      }
      return { value: 'Good', confidence: 0.45, source: 'heuristic' };
    },
  },

  // ── Govt. Land Rate ────────────────────────────────────────
  {
    fieldKey: 'govtLandRate',
    label: 'Govt. Approved Rate',
    section: 8,
    requires: ['classOfLocality'],
    predict: (fields) => {
      const locality = getVal(fields, 'classOfLocality');
      const trained = weights.govtRateByLocality?.[locality];

      if (trained) {
        return {
          value: `${trained.median}`,
          confidence: trainedConfidence(0.6, trained.count),
          source: 'ml',
        };
      }
      return null;
    },
  },

  // ── Recommended Land Rate ──────────────────────────────────
  {
    fieldKey: 'landRatePerUnit',
    label: 'Recommended Land Rate (₹)',
    section: 8,
    requires: ['classOfLocality'],
    predict: (fields) => {
      const locality = getVal(fields, 'classOfLocality');
      const vicinity = getVal(fields, 'vicinity');

      // Try exact match first: locality|vicinity
      const exactKey = `${locality}|${vicinity}`;
      const exactTrained = weights.marketRateByLocalityVicinity?.[exactKey];

      if (exactTrained) {
        return {
          value: `${exactTrained.median}`,
          confidence: trainedConfidence(0.65, exactTrained.count),
          source: 'ml',
        };
      }

      // Fallback: locality-only (average across all vicinities)
      const govtTrained = weights.govtRateByLocality?.[locality];
      if (govtTrained) {
        // Market rate is typically 2-3x govt rate
        const estimatedMarket = Math.round(govtTrained.median * 2.2);
        return {
          value: `${estimatedMarket}`,
          confidence: trainedConfidence(0.5, govtTrained.count),
          source: 'ml',
        };
      }

      return null;
    },
  },

  // ── Basis for Recommendation ───────────────────────────────
  {
    fieldKey: 'recommendedRateBasis',
    label: 'Basis for Recommendation',
    section: 8,
    requires: ['classOfLocality'],
    predict: (fields) => {
      const locality = getVal(fields, 'classOfLocality');
      const trained = weights.recommendedBasisByLocality?.[locality];

      if (trained && trained.mode) {
        return {
          value: trained.mode,
          confidence: trainedConfidence(0.7, trained.count),
          source: 'ml',
        };
      }

      return {
        value: 'As per local feedback, market survey, and prevailing rates in the area',
        confidence: 0.65,
        source: 'heuristic',
      };
    },
  },

  // ── Marketability ──────────────────────────────────────────
  {
    fieldKey: 'marketability',
    label: 'Marketability',
    section: 9,
    requires: ['classOfLocality'],
    predict: (fields) => {
      const locality = getVal(fields, 'classOfLocality');
      const roadWidth = getVal(fields, 'approachRoadWidth');

      // Try exact match: locality|roadWidth
      const key = `${locality}|${roadWidth}`;
      const trained = weights.marketabilityByLocalityRoad?.[key];

      if (trained && trained.mode) {
        return {
          value: trained.mode,
          confidence: trainedConfidence(0.6, trained.count),
          source: 'ml',
        };
      }

      // Heuristic fallback
      const fallbackMap: Record<string, string> = {
        'Elite': 'Excellent', 'Posh': 'Excellent',
        'High Class': 'Very Good', 'Upper Middle Class': 'Very Good',
        'Middle Class': 'Good', 'Lower Middle Class': 'Good',
      };
      return {
        value: fallbackMap[locality] || 'Good',
        confidence: 0.5,
        source: 'heuristic',
      };
    },
  },

  // ── Realizable % ───────────────────────────────────────────
  {
    fieldKey: 'realizablePct',
    label: 'Realizable Value %',
    section: 9,
    requires: [],
    predict: (fields) => {
      const marketability = getVal(fields, 'marketability');
      const trained = weights.realizableByMarketability?.[marketability];

      if (trained) {
        return {
          value: `${trained.median}`,
          confidence: trainedConfidence(0.65, trained.count),
          source: 'ml',
        };
      }

      // Fallback by locality
      const locality = getVal(fields, 'classOfLocality');
      if (['Elite', 'Posh'].includes(locality)) return { value: '92', confidence: 0.55, source: 'heuristic' };
      if (['High Class', 'Upper Middle Class'].includes(locality)) return { value: '90', confidence: 0.55, source: 'heuristic' };
      return { value: '85', confidence: 0.5, source: 'heuristic' };
    },
  },

  // ── Distress % ─────────────────────────────────────────────
  {
    fieldKey: 'distressPct',
    label: 'Distress/Forced Sale %',
    section: 9,
    requires: [],
    predict: (fields) => {
      // If realizable is already filled, calculate from it
      const realizablePct = getVal(fields, 'realizablePct');
      if (realizablePct) {
        const rPct = parseInt(realizablePct) || 85;
        const dPct = Math.max(rPct - 10, 65);
        return { value: `${dPct}`, confidence: 0.85, source: 'calculated' };
      }

      const marketability = getVal(fields, 'marketability');
      const trained = weights.distressByMarketability?.[marketability];

      if (trained) {
        return {
          value: `${trained.median}`,
          confidence: trainedConfidence(0.6, trained.count),
          source: 'ml',
        };
      }

      const locality = getVal(fields, 'classOfLocality');
      if (['Elite', 'Posh'].includes(locality)) return { value: '82', confidence: 0.5, source: 'heuristic' };
      if (['High Class', 'Upper Middle Class'].includes(locality)) return { value: '80', confidence: 0.5, source: 'heuristic' };
      return { value: '75', confidence: 0.45, source: 'heuristic' };
    },
  },

  // ── Replacement Cost ───────────────────────────────────────
  {
    fieldKey: 'replacementCost',
    label: 'Replacement Cost (₹)',
    section: 9,
    requires: ['floors'],
    predict: (fields) => {
      const floors = fields.floors;
      if (!Array.isArray(floors) || floors.length === 0) return null;

      let totalEstimated = 0;
      for (const f of floors) {
        const area = parseFloat(f.area) || 0;
        const rate = parseFloat(f.rate) || 0;
        totalEstimated += area * rate;
      }

      if (totalEstimated === 0) return null;
      return { value: `${Math.round(totalEstimated)}`, confidence: 0.85, source: 'calculated' };
    },
  },
];

// ─── Floor-level Prediction Rules ───────────────────────────────

export function predictFloorFields(
  fields: PredictionInput,
  floor: { id: string; name: string; area: string; rate: string; lifeYears: string; ageYears: string; depreciationPct: string }
): Record<string, Suggestion> {
  const suggestions: Record<string, Suggestion> = {};
  const structType = getVal(fields, 'structureType');
  const locality = getVal(fields, 'classOfLocality');

  // Life Years — from trained data
  if (!isFilled(floor.lifeYears) && structType) {
    const trained = weights.structureLifeSpans?.[structType];
    if (trained && trained.medianTotalLife) {
      suggestions[`floor_${floor.id}_lifeYears`] = {
        value: `${trained.medianTotalLife}`,
        confidence: trainedConfidence(0.75, trained.count),
        source: 'ml',
        label: `${floor.name || 'Floor'} — Life (Yr)`,
        section: 7,
        fieldKey: `floor_${floor.id}_lifeYears`,
      };
    } else {
      const life = STRUCTURE_LIFE_FALLBACK[structType];
      if (life) {
        suggestions[`floor_${floor.id}_lifeYears`] = {
          value: `${life}`,
          confidence: 0.65,
          source: 'heuristic',
          label: `${floor.name || 'Floor'} — Life (Yr)`,
          section: 7,
          fieldKey: `floor_${floor.id}_lifeYears`,
        };
      }
    }
  }

  // Depreciation %
  if (!isFilled(floor.depreciationPct) && isFilled(floor.lifeYears) && isFilled(floor.ageYears)) {
    const life = parseFloat(floor.lifeYears) || 0;
    const age = parseFloat(floor.ageYears) || 0;
    if (life > 0) {
      const dep = Math.round((age / life) * 100 * 100) / 100;
      suggestions[`floor_${floor.id}_depreciationPct`] = {
        value: `${Math.min(dep, 90)}`,
        confidence: 0.9,
        source: 'calculated',
        label: `${floor.name || 'Floor'} — Depreciation %`,
        section: 7,
        fieldKey: `floor_${floor.id}_depreciationPct`,
      };
    }
  }

  // Rate (₹/unit) — from trained data
  if (!isFilled(floor.rate) && locality) {
    const key = `${locality}|${structType}`;
    const trained = weights.floorRateByGroup?.[key];

    if (trained) {
      // The trained "floor rate" is per-floor value, we need per-sqft rate
      // Use market rate as better proxy
      const vicinity = getVal(fields, 'vicinity');
      const marketKey = `${locality}|${vicinity}`;
      const marketTrained = weights.marketRateByLocalityVicinity?.[marketKey];

      if (marketTrained) {
        suggestions[`floor_${floor.id}_rate`] = {
          value: `${marketTrained.median}`,
          confidence: trainedConfidence(0.55, marketTrained.count),
          source: 'ml',
          label: `${floor.name || 'Floor'} — Rate (₹)`,
          section: 7,
          fieldKey: `floor_${floor.id}_rate`,
        };
      }
    }

    // Fallback if no trained data
    if (!suggestions[`floor_${floor.id}_rate`]) {
      const govtTrained = weights.govtRateByLocality?.[locality];
      if (govtTrained) {
        // Floor rate ≈ 2x govt rate
        const rate = Math.round(govtTrained.median * 2);
        suggestions[`floor_${floor.id}_rate`] = {
          value: `${rate}`,
          confidence: trainedConfidence(0.4, govtTrained.count),
          source: 'ml',
          label: `${floor.name || 'Floor'} — Rate (₹)`,
          section: 7,
          fieldKey: `floor_${floor.id}_rate`,
        };
      }
    }
  }

  return suggestions;
}

// ─── Main Prediction Function ───────────────────────────────────

export function predictValuationFields(fields: PredictionInput): PredictionResult {
  const suggestions: Record<string, Suggestion> = {};

  // Count filled vs total fields
  let filledCount = 0;
  for (const key of ALL_FIELD_KEYS) {
    if (isFilled(fields[key])) filledCount++;
  }

  // Run each prediction rule
  for (const rule of PREDICTION_RULES) {
    // Skip if field is already filled
    if (isFilled(fields[rule.fieldKey])) continue;

    // Check if required inputs are available
    const hasRequirements = rule.requires.every((reqKey) => {
      if (reqKey === 'floors') return Array.isArray(fields.floors) && fields.floors.length > 0;
      return isFilled(fields[reqKey]);
    });

    if (!hasRequirements && rule.requires.length > 0) continue;

    // Run prediction
    const result = rule.predict(fields);
    if (result) {
      suggestions[rule.fieldKey] = {
        ...result,
        label: rule.label,
        section: rule.section,
        fieldKey: rule.fieldKey,
      };
    }
  }

  // Floor-level predictions
  if (Array.isArray(fields.floors)) {
    for (const floor of fields.floors) {
      const floorSuggestions = predictFloorFields(fields, floor);
      Object.assign(suggestions, floorSuggestions);
    }
  }

  // Calculate overall confidence
  const suggestionValues = Object.values(suggestions);
  const overallConfidence = suggestionValues.length > 0
    ? Math.round(suggestionValues.reduce((sum, s) => sum + s.confidence, 0) / suggestionValues.length * 100) / 100
    : 0;

  return {
    suggestions,
    filledCount,
    totalFields: ALL_FIELD_KEYS.length,
    overallConfidence,
  };
}
